import type { Concept } from "./types";

// Original teaching examples. JLPT labels are approximate curriculum groupings,
// not an official or exhaustive JLPT word list.
export const concepts: Concept[] = [
  {
    id: "v-maniau",
    type: "vocabulary",
    expression: "間に合う",
    reading: "まにあう",
    meaning: "to be in time; to make it in time",
    level: "N4",
    example: "電車に間に合いました。",
    exampleMeaning: "I made it in time for the train.",
    note: "Use に to mark the event you are in time for.",
    topic: "Getting around",
  },
  {
    id: "v-norikaeru",
    type: "vocabulary",
    expression: "乗り換える",
    reading: "のりかえる",
    meaning: "to transfer; to change trains",
    level: "N4",
    example: "東京駅で電車を乗り換えます。",
    exampleMeaning: "I change trains at Tokyo Station.",
    note: "で marks the place where you transfer.",
    topic: "Getting around",
  },
  {
    id: "v-yoyaku",
    type: "vocabulary",
    expression: "予約",
    reading: "よやく",
    meaning: "reservation; booking",
    level: "N4",
    example: "七時に予約をしています。",
    exampleMeaning: "I have a reservation for seven o’clock.",
    note: "予約する means to make a reservation.",
    topic: "Eating out",
  },
  {
    id: "v-osusume",
    type: "vocabulary",
    expression: "おすすめ",
    reading: "おすすめ",
    meaning: "recommendation",
    level: "N4",
    example: "おすすめは何ですか。",
    exampleMeaning: "What do you recommend?",
    note: "A useful question at a restaurant or café.",
    topic: "Eating out",
  },
  {
    id: "v-eki",
    type: "vocabulary",
    expression: "駅",
    reading: "えき",
    meaning: "train station",
    level: "N5",
    example: "駅はどこですか。",
    exampleMeaning: "Where is the station?",
    note: "Add a place name: 東京駅 means Tokyo Station.",
    topic: "Getting around",
  },
  {
    id: "v-kippu",
    type: "vocabulary",
    expression: "切符",
    reading: "きっぷ",
    meaning: "ticket",
    level: "N5",
    example: "切符を二枚ください。",
    exampleMeaning: "Two tickets, please.",
    note: "枚（まい）is the counter for flat things, including tickets.",
    topic: "Getting around",
  },
  {
    id: "v-mise",
    type: "vocabulary",
    expression: "店",
    reading: "みせ",
    meaning: "shop; store",
    level: "N5",
    example: "この店は九時に開きます。",
    exampleMeaning: "This shop opens at nine.",
    note: "お店 is a common polite form.",
    topic: "Shopping",
  },
  {
    id: "v-daijoubu",
    type: "vocabulary",
    expression: "大丈夫",
    reading: "だいじょうぶ",
    meaning: "all right; okay",
    level: "N5",
    example: "はい、大丈夫です。",
    exampleMeaning: "Yes, that’s fine.",
    note: "Its meaning depends on context; it can reassure or politely decline.",
    topic: "Everyday Japanese",
  },
  {
    id: "k-eki",
    type: "kanji",
    expression: "駅",
    reading: "エキ",
    meaning: "station",
    level: "N5",
    example: "駅前（えきまえ）",
    exampleMeaning: "in front of the station",
    note: "Look for this character on station signs and maps.",
    topic: "Getting around",
  },
  {
    id: "k-shoku",
    type: "kanji",
    expression: "食",
    reading: "ショク · た（べる）",
    meaning: "eat; food",
    level: "N5",
    example: "食べる（たべる）・食堂（しょくどう）",
    exampleMeaning: "to eat · dining hall",
    note: "A kanji’s reading changes with the word it appears in.",
    topic: "Eating out",
  },
  {
    id: "k-ryo",
    type: "kanji",
    expression: "旅",
    reading: "リョ · たび",
    meaning: "travel; journey",
    level: "N4",
    example: "旅行（りょこう）",
    exampleMeaning: "travel; a trip",
    note: "旅館（りょかん）is a traditional Japanese inn.",
    topic: "Staying in Japan",
  },
  {
    id: "k-sen",
    type: "kanji",
    expression: "線",
    reading: "セン",
    meaning: "line",
    level: "N4",
    example: "山手線（やまのてせん）",
    exampleMeaning: "the Yamanote Line",
    note: "Used in the names of train lines.",
    topic: "Getting around",
  },
  {
    id: "k-kai",
    type: "kanji",
    expression: "会",
    reading: "カイ · あ（う）",
    meaning: "meet; association",
    level: "N5",
    example: "会う（あう）・会社（かいしゃ）",
    exampleMeaning: "to meet · company",
    note: "友達に会います means I meet a friend.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-te-kudasai",
    type: "grammar",
    expression: "〜てください",
    reading: "てください",
    meaning: "please do …",
    level: "N5",
    example: "ここで待ってください。",
    exampleMeaning: "Please wait here.",
    note: "Attach ください to the て-form of a verb. 待つ becomes 待って.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-temo-ii",
    type: "grammar",
    expression: "〜てもいいですか",
    reading: "てもいいですか",
    meaning: "may I …?; is it okay to …?",
    level: "N5",
    example: "写真を撮ってもいいですか。",
    exampleMeaning: "May I take a photo?",
    note: "Verb て-form + もいいですか asks for permission politely.",
    topic: "Exploring Japan",
  },
  {
    id: "g-ta-koto",
    type: "grammar",
    expression: "〜たことがある",
    reading: "たことがある",
    meaning: "to have done … before",
    level: "N4",
    example: "日本に行ったことがあります。",
    exampleMeaning: "I have been to Japan before.",
    note: "Use a verb’s plain past form + ことがある to describe experience.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-tsumori",
    type: "grammar",
    expression: "〜つもりです",
    reading: "つもりです",
    meaning: "I intend to …; I plan to …",
    level: "N4",
    example: "明日、浅草に行くつもりです。",
    exampleMeaning: "I plan to go to Asakusa tomorrow.",
    note: "Use the dictionary form + つもりです for an intention.",
    topic: "Exploring Japan",
  },
  {
    id: "r-station",
    type: "reading",
    expression: "駅で",
    reading: "えきで",
    meaning: "At the station",
    level: "N5",
    example:
      "明日、友達と東京に行きます。九時に駅で会います。駅で切符を買います。電車は九時半に出ます。",
    exampleMeaning:
      "Tomorrow, I’m going to Tokyo with a friend. We’ll meet at the station at nine. We’ll buy tickets at the station. The train leaves at nine thirty.",
    note: "九時半（くじはん）means half past nine. 出ます（でます）means leaves here.",
    topic: "Getting around",
    question: "What time will you meet your friend?",
    answer: "At 9:00, at the station. The train leaves at 9:30.",
  },
  {
    id: "r-restaurant",
    type: "reading",
    expression: "小さなレストラン",
    reading: "ちいさなレストラン",
    meaning: "A small restaurant",
    level: "N4",
    example:
      "駅の近くに小さなレストランがあります。人気があるので、昨日予約しました。今日はそこで晩ご飯を食べるつもりです。おすすめの料理を聞いてみます。",
    exampleMeaning:
      "There’s a small restaurant near the station. It’s popular, so I made a reservation yesterday. I plan to have dinner there today. I’ll try asking what dishes they recommend.",
    note: "〜ので gives a reason. 〜てみます means to try doing something.",
    topic: "Eating out",
    question: "Why did the writer make a reservation?",
    answer: "Because the restaurant is popular.",
  },
];

export const conceptById = new Map(
  concepts.map((concept) => [concept.id, concept]),
);
export const typeLabels = {
  vocabulary: "Vocabulary",
  kanji: "Kanji",
  grammar: "Grammar",
  reading: "Reading",
};
