import type { Concept } from "./types";
import { expandedCurriculum } from "./curriculum-expansion";
import { vocabularyCorpus, vocabularySource } from "./jlpt-vocabulary";

type DraftConcept = Omit<
  Concept,
  "curriculumUnit" | "sequence" | "difficulty" | "prerequisites" | "source"
>;

// Original teaching examples. JLPT labels are approximate curriculum groupings,
// not an official or exhaustive JLPT word list.
const starterConcepts = [
  {
    id: "v-maniau",
    type: "vocabulary",
    expression: "間に合う",
    reading: "まにあう",
    meaning: "to be in time; to make it in time",
    level: "N4",
    example: "電車に間に合いました。",
    exampleMeaning: "I made it in time for the train.",
    note: "Use に to mark the event you are in time for.",
    topic: "Getting around",
  },
  {
    id: "v-norikaeru",
    type: "vocabulary",
    expression: "乗り換える",
    reading: "のりかえる",
    meaning: "to transfer; to change trains",
    level: "N4",
    example: "東京駅で電車を乗り換えます。",
    exampleMeaning: "I change trains at Tokyo Station.",
    note: "で marks the place where you transfer.",
    topic: "Getting around",
  },
  {
    id: "v-yoyaku",
    type: "vocabulary",
    expression: "予約",
    reading: "よやく",
    meaning: "reservation; booking",
    level: "N4",
    example: "七時に予約をしています。",
    exampleMeaning: "I have a reservation for seven o’clock.",
    note: "予約する means to make a reservation.",
    topic: "Eating out",
  },
  {
    id: "v-osusume",
    type: "vocabulary",
    expression: "おすすめ",
    reading: "おすすめ",
    meaning: "recommendation",
    level: "N4",
    example: "おすすめは何ですか。",
    exampleMeaning: "What do you recommend?",
    note: "A useful question at a restaurant or café.",
    topic: "Eating out",
  },
  {
    id: "v-eki",
    type: "vocabulary",
    expression: "駅",
    reading: "えき",
    meaning: "train station",
    level: "N5",
    example: "駅はどこですか。",
    exampleMeaning: "Where is the station?",
    note: "Add a place name: 東京駅 means Tokyo Station.",
    topic: "Getting around",
  },
  {
    id: "v-kippu",
    type: "vocabulary",
    expression: "切符",
    reading: "きっぷ",
    meaning: "ticket",
    level: "N5",
    example: "切符を二枚ください。",
    exampleMeaning: "Two tickets, please.",
    note: "枚（まい）is the counter for flat things, including tickets.",
    topic: "Getting around",
  },
  {
    id: "v-mise",
    type: "vocabulary",
    expression: "店",
    reading: "みせ",
    meaning: "shop; store",
    level: "N5",
    example: "この店は九時に開きます。",
    exampleMeaning: "This shop opens at nine.",
    note: "お店 is a common polite form.",
    topic: "Shopping",
  },
  {
    id: "v-daijoubu",
    type: "vocabulary",
    expression: "大丈夫",
    reading: "だいじょうぶ",
    meaning: "all right; okay",
    level: "N5",
    example: "はい、大丈夫です。",
    exampleMeaning: "Yes, that’s fine.",
    note: "Its meaning depends on context; it can reassure or politely decline.",
    topic: "Everyday Japanese",
  },
  {
    id: "k-eki",
    type: "kanji",
    expression: "駅",
    reading: "エキ",
    meaning: "station",
    level: "N5",
    example: "駅前（えきまえ）",
    exampleMeaning: "in front of the station",
    note: "Look for this character on station signs and maps.",
    topic: "Getting around",
  },
  {
    id: "k-shoku",
    type: "kanji",
    expression: "食",
    reading: "ショク · た（べる）",
    meaning: "eat; food",
    level: "N5",
    example: "食べる（たべる）・食堂（しょくどう）",
    exampleMeaning: "to eat · dining hall",
    note: "A kanji’s reading changes with the word it appears in.",
    topic: "Eating out",
  },
  {
    id: "k-ryo",
    type: "kanji",
    expression: "旅",
    reading: "リョ · たび",
    meaning: "travel; journey",
    level: "N4",
    example: "旅行（りょこう）",
    exampleMeaning: "travel; a trip",
    note: "旅館（りょかん）is a traditional Japanese inn.",
    topic: "Staying in Japan",
  },
  {
    id: "k-sen",
    type: "kanji",
    expression: "線",
    reading: "セン",
    meaning: "line",
    level: "N4",
    example: "山手線（やまのてせん）",
    exampleMeaning: "the Yamanote Line",
    note: "Used in the names of train lines.",
    topic: "Getting around",
  },
  {
    id: "k-kai",
    type: "kanji",
    expression: "会",
    reading: "カイ · あ（う）",
    meaning: "meet; association",
    level: "N5",
    example: "会う（あう）・会社（かいしゃ）",
    exampleMeaning: "to meet · company",
    note: "友達に会います means I meet a friend.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-te-kudasai",
    type: "grammar",
    expression: "〜てください",
    reading: "てください",
    meaning: "please do …",
    level: "N5",
    example: "ここで待ってください。",
    exampleMeaning: "Please wait here.",
    note: "Attach ください to the て-form of a verb. 待つ becomes 待って.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-temo-ii",
    type: "grammar",
    expression: "〜てもいいですか",
    reading: "てもいいですか",
    meaning: "may I …?; is it okay to …?",
    level: "N5",
    example: "写真を撮ってもいいですか。",
    exampleMeaning: "May I take a photo?",
    note: "Verb て-form + もいいですか asks for permission politely.",
    topic: "Exploring Japan",
  },
  {
    id: "g-ta-koto",
    type: "grammar",
    expression: "〜たことがある",
    reading: "たことがある",
    meaning: "to have done … before",
    level: "N4",
    example: "日本に行ったことがあります。",
    exampleMeaning: "I have been to Japan before.",
    note: "Use a verb’s plain past form + ことがある to describe experience.",
    topic: "Everyday Japanese",
  },
  {
    id: "g-tsumori",
    type: "grammar",
    expression: "〜つもりです",
    reading: "つもりです",
    meaning: "I intend to …; I plan to …",
    level: "N4",
    example: "明日、浅草に行くつもりです。",
    exampleMeaning: "I plan to go to Asakusa tomorrow.",
    note: "Use the dictionary form + つもりです for an intention.",
    topic: "Exploring Japan",
  },
  {
    id: "r-station",
    type: "reading",
    expression: "駅で",
    reading: "えきで",
    meaning: "At the station",
    level: "N5",
    example:
      "明日、友達と東京に行きます。九時に駅で会います。駅で切符を買います。電車は九時半に出ます。",
    exampleMeaning:
      "Tomorrow, I’m going to Tokyo with a friend. We’ll meet at the station at nine. We’ll buy tickets at the station. The train leaves at nine thirty.",
    note: "九時半（くじはん）means half past nine. 出ます（でます）means leaves here.",
    topic: "Getting around",
    question: "What time will you meet your friend?",
    answer: "At 9:00, at the station. The train leaves at 9:30.",
  },
  {
    id: "r-restaurant",
    type: "reading",
    expression: "小さなレストラン",
    reading: "ちいさなレストラン",
    meaning: "A small restaurant",
    level: "N4",
    example:
      "駅の近くに小さなレストランがあります。人気があるので、昨日予約しました。今日はそこで晩ご飯を食べるつもりです。おすすめの料理を聞いてみます。",
    exampleMeaning:
      "There’s a small restaurant near the station. It’s popular, so I made a reservation yesterday. I plan to have dinner there today. I’ll try asking what dishes they recommend.",
    note: "〜ので gives a reason. 〜てみます means to try doing something.",
    topic: "Eating out",
    question: "Why did the writer make a reservation?",
    answer: "Because the restaurant is popular.",
  },
] satisfies DraftConcept[];

const curriculumAdditions = [
  { id: "v-watashi", type: "vocabulary", expression: "私", reading: "わたし", meaning: "I; me", level: "N5", example: "私はダニエルです。", exampleMeaning: "I am Daniel.", note: "私 is a neutral first-person word. In casual speech, people often omit it when the subject is clear.", topic: "Introductions" },
  { id: "v-kore", type: "vocabulary", expression: "これ", reading: "これ", meaning: "this", level: "N5", example: "これは私のかばんです。", exampleMeaning: "This is my bag.", note: "Use これ for a thing near the speaker.", topic: "Everyday Japanese" },
  { id: "v-aru", type: "vocabulary", expression: "ある", reading: "ある", meaning: "to exist; to have (inanimate)", level: "N5", example: "机の上に本があります。", exampleMeaning: "There is a book on the desk.", note: "Use あります for things, places, and events rather than people or animals.", topic: "Everyday Japanese" },
  { id: "v-iru", type: "vocabulary", expression: "いる", reading: "いる", meaning: "to exist; to be (animate)", level: "N5", example: "教室に先生がいます。", exampleMeaning: "There is a teacher in the classroom.", note: "Use います for people and animals.", topic: "Everyday Japanese" },
  { id: "v-iku", type: "vocabulary", expression: "行く", reading: "いく", meaning: "to go", level: "N5", example: "明日、学校に行きます。", exampleMeaning: "I will go to school tomorrow.", note: "A destination is commonly marked with に or へ.", topic: "Daily routines" },
  { id: "v-taberu", type: "vocabulary", expression: "食べる", reading: "たべる", meaning: "to eat", level: "N5", example: "朝ご飯を食べます。", exampleMeaning: "I eat breakfast.", note: "The thing eaten is marked with を.", topic: "Daily routines" },
  { id: "v-nomu", type: "vocabulary", expression: "飲む", reading: "のむ", meaning: "to drink", level: "N5", example: "水を飲みます。", exampleMeaning: "I drink water.", note: "飲み物 means a drink or beverage.", topic: "Eating out" },
  { id: "v-kau", type: "vocabulary", expression: "買う", reading: "かう", meaning: "to buy", level: "N5", example: "コンビニでパンを買います。", exampleMeaning: "I buy bread at a convenience store.", note: "Use で for the place where an action happens.", topic: "Shopping" },
  { id: "v-jikan", type: "vocabulary", expression: "時間", reading: "じかん", meaning: "time; hour", level: "N5", example: "今、時間がありますか。", exampleMeaning: "Do you have time now?", note: "〜時間 means a duration, while 時 is used for a clock time.", topic: "Daily routines" },
  { id: "v-hayai", type: "vocabulary", expression: "早い", reading: "はやい", meaning: "early; fast", level: "N5", example: "この電車は早いです。", exampleMeaning: "This train is fast.", note: "早い can describe being early in time or fast in speed.", topic: "Getting around" },
  { id: "v-hitsuyou", type: "vocabulary", expression: "必要", reading: "ひつよう", meaning: "necessary; needed", level: "N4", example: "パスポートが必要です。", exampleMeaning: "A passport is necessary.", note: "Use が必要です to say that something is needed.", topic: "Travel preparation" },
  { id: "v-yotei", type: "vocabulary", expression: "予定", reading: "よてい", meaning: "plan; schedule", level: "N4", example: "週末の予定はありますか。", exampleMeaning: "Do you have plans for the weekend?", note: "予定 can describe a personal plan or a scheduled event.", topic: "Plans" },
  { id: "v-junbi", type: "vocabulary", expression: "準備", reading: "じゅんび", meaning: "preparation", level: "N4", example: "旅行の準備をしています。", exampleMeaning: "I am preparing for the trip.", note: "準備する means to prepare.", topic: "Travel preparation" },
  { id: "v-benri", type: "vocabulary", expression: "便利", reading: "べんり", meaning: "convenient", level: "N4", example: "このアプリは便利です。", exampleMeaning: "This app is convenient.", note: "便利な comes before a noun: 便利なアプリ.", topic: "Everyday Japanese" },
  { id: "v-kimeru", type: "vocabulary", expression: "決める", reading: "きめる", meaning: "to decide", level: "N4", example: "会う時間を決めましょう。", exampleMeaning: "Let’s decide what time to meet.", note: "Use を決める for the thing you decide.", topic: "Plans" },
  { id: "v-shiraberu", type: "vocabulary", expression: "調べる", reading: "しらべる", meaning: "to look up; investigate", level: "N4", example: "ホテルの場所を調べます。", exampleMeaning: "I will look up the hotel’s location.", note: "Use it for checking information in a guidebook, map, or online.", topic: "Travel preparation" },
  { id: "v-renraku", type: "vocabulary", expression: "連絡", reading: "れんらく", meaning: "contact; message", level: "N4", example: "着いたら連絡してください。", exampleMeaning: "Please contact me when you arrive.", note: "連絡する means to contact someone.", topic: "Daily routines" },
  { id: "v-basho", type: "vocabulary", expression: "場所", reading: "ばしょ", meaning: "place; location", level: "N4", example: "集合場所は駅の前です。", exampleMeaning: "The meeting place is in front of the station.", note: "集合 means gathering or meeting up.", topic: "Getting around" },
  { id: "v-saki", type: "vocabulary", expression: "先", reading: "さき", meaning: "ahead; destination; earlier", level: "N4", example: "先にホテルへ行きます。", exampleMeaning: "I will go to the hotel first.", note: "先に means before someone else or before another action.", topic: "Getting around" },
  { id: "k-nichi", type: "kanji", expression: "日", reading: "ニチ · ひ", meaning: "day; sun", level: "N5", example: "日曜日（にちようび）・毎日（まいにち）", exampleMeaning: "Sunday · every day", note: "The reading changes with the word. Learn common compounds rather than isolated readings.", topic: "Time" },
  { id: "k-getsu", type: "kanji", expression: "月", reading: "ゲツ · つき", meaning: "month; moon", level: "N5", example: "一月（いちがつ）・月曜日（げつようび）", exampleMeaning: "January · Monday", note: "月 is used in month names and days of the week.", topic: "Time" },
  { id: "k-ka", type: "kanji", expression: "火", reading: "カ · ひ", meaning: "fire", level: "N5", example: "火曜日（かようび）・火山（かざん）", exampleMeaning: "Tuesday · volcano", note: "The small strokes resemble flames.", topic: "Time" },
  { id: "k-sui", type: "kanji", expression: "水", reading: "スイ · みず", meaning: "water", level: "N5", example: "水曜日（すいようび）・水（みず）", exampleMeaning: "Wednesday · water", note: "Useful on menus and when asking for a drink.", topic: "Eating out" },
  { id: "k-moku", type: "kanji", expression: "木", reading: "モク · き", meaning: "tree; wood", level: "N5", example: "木曜日（もくようび）・木（き）", exampleMeaning: "Thursday · tree", note: "The shape is a simplified picture of a tree.", topic: "Time" },
  { id: "k-kin", type: "kanji", expression: "金", reading: "キン · かね", meaning: "gold; money", level: "N5", example: "金曜日（きんようび）・お金（おかね）", exampleMeaning: "Friday · money", note: "お金 is the everyday word for money.", topic: "Shopping" },
  { id: "k-do", type: "kanji", expression: "土", reading: "ド · つち", meaning: "earth; soil", level: "N5", example: "土曜日（どようび）", exampleMeaning: "Saturday", note: "It is especially useful as part of 土曜日.", topic: "Time" },
  { id: "k-hon", type: "kanji", expression: "本", reading: "ホン · もと", meaning: "book; origin", level: "N5", example: "日本（にほん）・本（ほん）", exampleMeaning: "Japan · book", note: "The extra line marks the root of 木, the tree.", topic: "Everyday Japanese" },
  { id: "k-shin", type: "kanji", expression: "新", reading: "シン · あたら（しい）", meaning: "new", level: "N4", example: "新しい店（あたらしいみせ）", exampleMeaning: "a new shop", note: "新しい is an i-adjective.", topic: "Shopping" },
  { id: "k-kyuu", type: "kanji", expression: "古", reading: "コ · ふる（い）", meaning: "old", level: "N4", example: "古い町（ふるいまち）", exampleMeaning: "an old town", note: "古い is an i-adjective and contrasts with 新しい.", topic: "Exploring Japan" },
  { id: "k-kinai", type: "kanji", expression: "近", reading: "キン · ちか（い）", meaning: "near", level: "N4", example: "駅の近く（えきのちかく）", exampleMeaning: "near the station", note: "近く is a useful noun-like form meaning nearby.", topic: "Getting around" },
  { id: "k-en", type: "kanji", expression: "遠", reading: "エン · とお（い）", meaning: "far", level: "N4", example: "駅から遠い（えきからとおい）", exampleMeaning: "far from the station", note: "遠い is an i-adjective and contrasts with 近い.", topic: "Getting around" },
  { id: "k-ryou", type: "kanji", expression: "料", reading: "リョウ", meaning: "fee; material", level: "N4", example: "料金（りょうきん）", exampleMeaning: "fee; fare", note: "料金 is common on transport and hotel information.", topic: "Travel preparation" },
  { id: "k-ri", type: "kanji", expression: "理", reading: "リ", meaning: "reason; logic", level: "N4", example: "料理（りょうり）", exampleMeaning: "cooking; cuisine", note: "料理 is a practical word for food and dishes.", topic: "Eating out" },
  { id: "k-ba", type: "kanji", expression: "場", reading: "ジョウ · ば", meaning: "place; scene", level: "N4", example: "場所（ばしょ）", exampleMeaning: "place; location", note: "場 is often read ば in everyday compound words.", topic: "Getting around" },
  { id: "k-sho", type: "kanji", expression: "所", reading: "ショ · ところ", meaning: "place", level: "N4", example: "住所（じゅうしょ）", exampleMeaning: "address", note: "住所 is important on forms and reservations.", topic: "Travel preparation" },
  { id: "g-wa", type: "grammar", expression: "〜は〜です", reading: "は です", meaning: "topic + description", level: "N5", example: "これは日本語の本です。", exampleMeaning: "This is a Japanese book.", note: "は marks the topic. It is pronounced わ in this grammar pattern.", topic: "Introductions" },
  { id: "g-o", type: "grammar", expression: "〜を〜ます", reading: "を ます", meaning: "object + action", level: "N5", example: "毎朝コーヒーを飲みます。", exampleMeaning: "I drink coffee every morning.", note: "を marks the direct object of an action.", topic: "Daily routines" },
  { id: "g-ni-de", type: "grammar", expression: "に／で", reading: "に で", meaning: "destination or location / place of action", level: "N5", example: "駅に行きます。駅で切符を買います。", exampleMeaning: "I go to the station. I buy a ticket at the station.", note: "に marks a destination; で marks the place where an action happens.", topic: "Getting around" },
  { id: "g-masu", type: "grammar", expression: "〜ます", reading: "ます", meaning: "polite present and future", level: "N5", example: "明日、東京へ行きます。", exampleMeaning: "I will go to Tokyo tomorrow.", note: "The same polite form can express a habit, present action, or future plan depending on context.", topic: "Daily routines" },
  { id: "g-nai", type: "grammar", expression: "〜ません", reading: "ません", meaning: "polite negative", level: "N5", example: "今日は行きません。", exampleMeaning: "I will not go today.", note: "ません is the polite negative partner of ます.", topic: "Daily routines" },
  { id: "g-kara", type: "grammar", expression: "〜から", reading: "から", meaning: "because; from", level: "N5", example: "雨ですから、家にいます。", exampleMeaning: "Because it is raining, I will stay home.", note: "から can give a reason. It also marks a starting point in time or place.", topic: "Everyday Japanese" },
  { id: "g-to-omou", type: "grammar", expression: "〜と思います", reading: "とおもいます", meaning: "I think that …", level: "N4", example: "明日は雨だと思います。", exampleMeaning: "I think it will rain tomorrow.", note: "Put a plain-form statement before と思います.", topic: "Plans" },
  { id: "g-nagara", type: "grammar", expression: "〜ながら", reading: "ながら", meaning: "while doing …", level: "N4", example: "音楽を聞きながら勉強します。", exampleMeaning: "I study while listening to music.", note: "Attach ながら to the verb stem: 聞きます becomes 聞きながら.", topic: "Daily routines" },
  { id: "g-nakereba", type: "grammar", expression: "〜なければならない", reading: "なければならない", meaning: "must; have to …", level: "N4", example: "明日、早く起きなければなりません。", exampleMeaning: "I have to get up early tomorrow.", note: "A common shorter spoken form is 〜なければならない or 〜なくてはいけない.", topic: "Daily routines" },
  { id: "g-shi", type: "grammar", expression: "〜し", reading: "し", meaning: "and; because (giving multiple reasons)", level: "N4", example: "この店は安いし、駅から近いです。", exampleMeaning: "This shop is cheap and close to the station.", note: "し can add reasons or qualities without presenting an exhaustive list.", topic: "Shopping" },
  { id: "g-sou", type: "grammar", expression: "〜そうです", reading: "そうです", meaning: "looks; seems …", level: "N4", example: "このケーキはおいしそうです。", exampleMeaning: "This cake looks delicious.", note: "Attach そう to the adjective stem: おいしい becomes おいしそう.", topic: "Eating out" },
  { id: "g-teshimau", type: "grammar", expression: "〜てしまう", reading: "てしまう", meaning: "finish; unfortunately do …", level: "N4", example: "電車で寝てしまいました。", exampleMeaning: "I ended up falling asleep on the train.", note: "It can express completion or an unintended result. In conversation, てしまう often becomes ちゃう.", topic: "Getting around" },
  { id: "r-n5-menu", type: "reading", expression: "カフェのメニュー", reading: "かふぇのめにゅー", meaning: "A café menu", level: "N5", example: "コーヒーは三百円です。お茶は二百五十円です。ケーキは四百円です。", exampleMeaning: "Coffee is 300 yen. Tea is 250 yen. Cake is 400 yen.", note: "Look for prices and item names first when reading a simple menu.", topic: "Eating out", question: "Which item costs 250 yen?", answer: "Tea costs 250 yen." },
  { id: "r-n5-message", type: "reading", expression: "友達へのメッセージ", reading: "ともだちへのめっせーじ", meaning: "A message to a friend", level: "N5", example: "田中さんへ。明日、二時に駅で会いましょう。駅の前にいます。", exampleMeaning: "To Tanaka: Let’s meet at the station at two tomorrow. I will be in front of the station.", note: "へ after a name marks who a note or message is addressed to.", topic: "Getting around", question: "Where will the writer wait?", answer: "In front of the station." },
  { id: "r-n4-notice", type: "reading", expression: "休みのお知らせ", reading: "やすみのおしらせ", meaning: "A closure notice", level: "N4", example: "来週の月曜日は店が休みです。火曜日から金曜日までは、午前十時から午後六時まで開いています。", exampleMeaning: "The shop is closed next Monday. From Tuesday through Friday, it is open from 10 a.m. to 6 p.m.", note: "Notices often give dates, days, and opening hours. Find those facts before translating every word.", topic: "Shopping", question: "When is the shop closed?", answer: "It is closed next Monday." },
  { id: "r-n4-plan", type: "reading", expression: "週末の予定", reading: "しゅうまつのよてい", meaning: "Weekend plans", level: "N4", example: "土曜日は友達と映画を見に行く予定です。映画の後で、近くのレストランで晩ご飯を食べるつもりです。", exampleMeaning: "On Saturday, I plan to go see a movie with a friend. After the movie, I intend to have dinner at a nearby restaurant.", note: "予定です and つもりです both describe plans, but they have slightly different nuance.", topic: "Plans", question: "What does the writer plan to do after the movie?", answer: "Have dinner at a nearby restaurant." },
  { id: "l-n5-station", type: "listening", expression: "駅の案内", reading: "えきのあんない", meaning: "Station announcement", level: "N5", example: "次の電車は三番線から出ます。東京駅まで行きます。", exampleMeaning: "The next train leaves from platform three. It goes to Tokyo Station.", note: "This is a listening-script item. Read it once, then cover it and try to catch the platform and destination from memory.", topic: "Getting around", question: "Which platform does the train leave from?", answer: "Platform three." },
  { id: "l-n5-shop", type: "listening", expression: "店での会話", reading: "みせでのかいわ", meaning: "A conversation in a shop", level: "N5", example: "店員：いらっしゃいませ。客：このかばんはいくらですか。店員：二千円です。", exampleMeaning: "Clerk: Welcome. Customer: How much is this bag? Clerk: It is 2,000 yen.", note: "This is a listening-script item. Focus on the question phrase いくらですか and the price.", topic: "Shopping", question: "How much is the bag?", answer: "2,000 yen." },
  { id: "l-n4-call", type: "listening", expression: "電話の伝言", reading: "でんわのでんごん", meaning: "A phone message", level: "N4", example: "もしもし、田中です。明日の会議は十時からです。少し早く来て、資料の準備を手伝ってください。", exampleMeaning: "Hello, this is Tanaka. Tomorrow’s meeting starts at ten. Please come a little early and help prepare the materials.", note: "This is a listening-script item. Identify the time and the requested action.", topic: "Daily routines", question: "What does Tanaka ask the listener to do?", answer: "Come early and help prepare the materials." },
  { id: "l-n4-direction", type: "listening", expression: "道を聞く", reading: "みちをきく", meaning: "Asking for directions", level: "N4", example: "すみません、郵便局へ行きたいんですが。あの信号を右に曲がって、二つ目の角を左です。", exampleMeaning: "Excuse me, I would like to go to the post office. Turn right at that traffic light, then left at the second corner.", note: "This is a listening-script item. Break directions into actions and landmarks.", topic: "Getting around", question: "What should the listener do at the traffic light?", answer: "Turn right." },
] satisfies DraftConcept[];

const topicUnits = {
  N5: {
    "Core vocabulary": "N5 · Units 1–6: Core vocabulary",
    "Introductions": "N5 · Unit 1: Introductions",
    "Everyday Japanese": "N5 · Unit 2: Everyday basics",
    "Daily routines": "N5 · Unit 3: Daily routines",
    "Time": "N5 · Unit 3: Time and routines",
    "Getting around": "N5 · Unit 4: Places and movement",
    "Shopping": "N5 · Unit 5: Buying things",
    "Eating out": "N5 · Unit 6: Food and requests",
  },
  N4: {
    "Core vocabulary": "N4 · Units 7–11: Core vocabulary",
    "Daily routines": "N4 · Unit 7: Daily routines and communication",
    "Everyday Japanese": "N4 · Unit 7: Daily routines and communication",
    "Plans": "N4 · Unit 8: Plans and reasons",
    "Getting around": "N4 · Unit 9: Movement and directions",
    "Exploring Japan": "N4 · Unit 9: Movement and directions",
    "Shopping": "N4 · Unit 10: Services and practical texts",
    "Eating out": "N4 · Unit 10: Services and practical texts",
    "Travel preparation": "N4 · Unit 11: Travel preparation",
    "Staying in Japan": "N4 · Unit 11: Travel preparation",
  },
} as const;
const unitOrder = [
  "N5 · Units 1–6: Core vocabulary",
  "N5 · Unit 1: Introductions",
  "N5 · Unit 2: Everyday basics",
  "N5 · Unit 3: Daily routines",
  "N5 · Unit 3: Time and routines",
  "N5 · Unit 4: Places and movement",
  "N5 · Unit 5: Buying things",
  "N5 · Unit 6: Food and requests",
  "N4 · Units 7–11: Core vocabulary",
  "N4 · Unit 7: Daily routines and communication",
  "N4 · Unit 8: Plans and reasons",
  "N4 · Unit 9: Movement and directions",
  "N4 · Unit 10: Services and practical texts",
  "N4 · Unit 11: Travel preparation",
];
const unitIndex = new Map(unitOrder.map((unit, index) => [unit, index]));
const typeOrder = { vocabulary: 0, kanji: 1, grammar: 2, reading: 3, listening: 4 } as const;
const sourceFor = (level: "N5" | "N4") => `Original teaching example; aligned to the JLPT ${level} level summary.`;
const vocabularyKey = (expression: string, reading: string) =>
  `${expression.replace(/[\s・;；〜～]/g, "")}/${reading.replace(/[\s・;；〜～]/g, "")}`;
const legacyVocabulary = [...starterConcepts, ...curriculumAdditions, ...expandedCurriculum]
  .filter((concept) => concept.type === "vocabulary")
  .map((concept) => [vocabularyKey(concept.expression, concept.reading), concept.id] as const);
const legacyVocabularyIds = new Map(legacyVocabulary);
const vocabularyConcepts = vocabularyCorpus.map((concept) => ({
  ...concept,
  id: legacyVocabularyIds.get(vocabularyKey(concept.expression, concept.reading)) ?? concept.id,
}));
const nonVocabularyConcepts = [...starterConcepts, ...curriculumAdditions, ...expandedCurriculum].filter(
  (concept) => concept.type !== "vocabulary",
);
export const concepts: Concept[] = [
  ...nonVocabularyConcepts,
  ...vocabularyConcepts,
]
  .sort((a, b) => {
    const unitA = topicUnits[a.level][a.topic as never] ?? `${a.level} · Core study`;
    const unitB = topicUnits[b.level][b.topic as never] ?? `${b.level} · Core study`;
    return (unitIndex.get(unitA) ?? 99) - (unitIndex.get(unitB) ?? 99) || typeOrder[a.type] - typeOrder[b.type];
  })
  .map((concept, index) => ({
    ...concept,
    curriculumUnit: topicUnits[concept.level][concept.topic as never] ?? `${concept.level} · Core study`,
    sequence: index + 1,
    difficulty: (concept.level === "N5" ? (concept.type === "reading" || concept.type === "listening" ? 3 : 1) : concept.type === "reading" || concept.type === "listening" ? 4 : 3) as 1 | 2 | 3 | 4 | 5,
    prerequisites: concept.level === "N4" ? ["N5 foundations"] : [],
    source: concept.type === "vocabulary" ? vocabularySource : sourceFor(concept.level),
  }));

export const conceptById = new Map(
  concepts.map((concept) => [concept.id, concept]),
);
export const typeLabels = {
  vocabulary: "Vocabulary",
  kanji: "Kanji",
  grammar: "Grammar",
  reading: "Reading",
  listening: "Listening",
};
