import type { Concept } from "./types";

export type CurriculumDraft = Omit<
  Concept,
  "curriculumUnit" | "sequence" | "difficulty" | "prerequisites" | "source"
>;

type Word = [
  id: string,
  expression: string,
  reading: string,
  meaning: string,
  example: string,
  exampleMeaning: string,
];

function words(
  level: "N5" | "N4",
  topic: string,
  items: Word[],
): CurriculumDraft[] {
  return items.map(([id, expression, reading, meaning, example, exampleMeaning]) => ({
    id,
    type: "vocabulary",
    expression,
    reading,
    meaning,
    level,
    example,
    exampleMeaning,
    note: `Learn ${expression} in its sentence, then say the sentence aloud with a detail that is true for you.`,
    topic,
  }));
}

type Character = [
  id: string,
  expression: string,
  reading: string,
  meaning: string,
  example: string,
  exampleMeaning: string,
];

function kanji(
  level: "N5" | "N4",
  topic: string,
  items: Character[],
): CurriculumDraft[] {
  return items.map(([id, expression, reading, meaning, example, exampleMeaning]) => ({
    id,
    type: "kanji",
    expression,
    reading,
    meaning,
    level,
    example,
    exampleMeaning,
    note: `Recognize ${expression} in the familiar word above before trying to write it from memory.`,
    topic,
  }));
}

const n5Vocabulary = [
  ...words("N5", "Introductions", [
    ["v-n5-namae", "名前", "なまえ", "name", "お名前は何ですか。", "What is your name?"],
    ["v-n5-gakusei", "学生", "がくせい", "student", "私は学生です。", "I am a student."],
    ["v-n5-sensei", "先生", "せんせい", "teacher; instructor", "先生は教室にいます。", "The teacher is in the classroom."],
    ["v-n5-kuni", "国", "くに", "country", "私の国はアメリカです。", "My country is the United States."],
    ["v-n5-nihongo", "日本語", "にほんご", "Japanese language", "日本語を勉強しています。", "I am studying Japanese."],
    ["v-n5-denwa", "電話", "でんわ", "telephone; phone call", "あとで電話します。", "I will call later."],
    ["v-n5-kazoku", "家族", "かぞく", "family", "家族は四人です。", "There are four people in my family."],
    ["v-n5-chichi", "父", "ちち", "my father", "父は会社員です。", "My father is an office worker."],
    ["v-n5-haha", "母", "はは", "my mother", "母は料理が上手です。", "My mother is good at cooking."],
  ]),
  ...words("N5", "Everyday Japanese", [
    ["v-n5-hon", "本", "ほん", "book", "この本は面白いです。", "This book is interesting."],
    ["v-n5-pen", "ペン", "ぺん", "pen", "青いペンを使います。", "I use a blue pen."],
    ["v-n5-kaban", "かばん", "かばん", "bag", "かばんは机の下です。", "The bag is under the desk."],
    ["v-n5-heya", "部屋", "へや", "room", "部屋にテレビがあります。", "There is a television in the room."],
    ["v-n5-ie", "家", "いえ", "house; home", "七時に家へ帰ります。", "I return home at seven."],
    ["v-n5-machi", "町", "まち", "town; neighborhood", "この町は静かです。", "This town is quiet."],
    ["v-n5-kyou", "今日", "きょう", "today", "今日は土曜日です。", "Today is Saturday."],
    ["v-n5-ashita", "明日", "あした", "tomorrow", "明日は休みです。", "Tomorrow is a day off."],
    ["v-n5-kinou", "昨日", "きのう", "yesterday", "昨日、映画を見ました。", "Yesterday, I watched a movie."],
    ["v-n5-ima", "今", "いま", "now", "今は三時です。", "It is three o’clock now."],
    ["v-n5-takusan", "たくさん", "たくさん", "many; much", "本がたくさんあります。", "There are many books."],
  ]),
  ...words("N5", "Daily routines", [
    ["v-n5-okiru", "起きる", "おきる", "to get up", "毎朝六時に起きます。", "I get up at six every morning."],
    ["v-n5-neru", "寝る", "ねる", "to sleep; go to bed", "十一時に寝ます。", "I go to bed at eleven."],
    ["v-n5-hataraku", "働く", "はたらく", "to work", "父は銀行で働いています。", "My father works at a bank."],
    ["v-n5-yasumu", "休む", "やすむ", "to rest; take a day off", "日曜日は家で休みます。", "I rest at home on Sunday."],
    ["v-n5-benkyou", "勉強", "べんきょう", "study", "夜、日本語を勉強します。", "I study Japanese at night."],
    ["v-n5-asa", "朝", "あさ", "morning", "朝はコーヒーを飲みます。", "I drink coffee in the morning."],
    ["v-n5-hiru", "昼", "ひる", "midday; daytime", "昼に友達と食べます。", "I eat with a friend at noon."],
    ["v-n5-yoru", "夜", "よる", "night; evening", "夜は涼しいです。", "The night is cool."],
    ["v-n5-mainichi", "毎日", "まいにち", "every day", "毎日、漢字を読みます。", "I read kanji every day."],
    ["v-n5-shuukan", "週間", "しゅうかん", "week", "一週間、日本にいます。", "I will be in Japan for one week."],
  ]),
  ...words("N5", "Getting around", [
    ["v-n5-gakkou", "学校", "がっこう", "school", "学校は駅の近くです。", "The school is near the station."],
    ["v-n5-byoin", "病院", "びょういん", "hospital", "病院はあそこです。", "The hospital is over there."],
    ["v-n5-ginkou", "銀行", "ぎんこう", "bank", "銀行でお金を下ろします。", "I withdraw money at the bank."],
    ["v-n5-yuubinkyoku", "郵便局", "ゆうびんきょく", "post office", "郵便局はどこですか。", "Where is the post office?"],
    ["v-n5-migi", "右", "みぎ", "right", "次の角を右です。", "It is right at the next corner."],
    ["v-n5-hidari", "左", "ひだり", "left", "左に曲がってください。", "Please turn left."],
    ["v-n5-mae", "前", "まえ", "front; before", "駅の前で待ちます。", "I will wait in front of the station."],
    ["v-n5-ushiro", "後ろ", "うしろ", "behind", "店の後ろに公園があります。", "There is a park behind the store."],
    ["v-n5-aruku", "歩く", "あるく", "to walk", "駅まで歩きます。", "I walk to the station."],
  ]),
  ...words("N5", "Shopping", [
    ["v-n5-ikura", "いくら", "いくら", "how much", "これはいくらですか。", "How much is this?"],
    ["v-n5-en", "円", "えん", "yen", "全部で千円です。", "It is one thousand yen in total."],
    ["v-n5-takai", "高い", "たかい", "expensive; high", "この時計は高いです。", "This watch is expensive."],
    ["v-n5-yasui", "安い", "やすい", "cheap; inexpensive", "あの店は安いです。", "That shop is inexpensive."],
    ["v-n5-mise", "見せる", "みせる", "to show", "パスポートを見せてください。", "Please show your passport."],
    ["v-n5-omise", "お店", "おみせ", "shop; store", "いいお店を知っていますか。", "Do you know a good shop?"],
    ["v-n5-kore-sore", "それ", "それ", "that", "それをください。", "That one, please."],
  ]),
  ...words("N5", "Eating out", [
    ["v-n5-mizu", "水", "みず", "water", "水をください。", "Water, please."],
    ["v-n5-ocha", "お茶", "おちゃ", "tea", "お茶を飲みませんか。", "Would you like to drink tea?"],
    ["v-n5-gohan", "ご飯", "ごはん", "meal; cooked rice", "ご飯を食べましょう。", "Let’s eat a meal."],
    ["v-n5-pan", "パン", "ぱん", "bread", "朝、パンを食べます。", "I eat bread in the morning."],
    ["v-n5-niku", "肉", "にく", "meat", "私は肉を食べません。", "I do not eat meat."],
    ["v-n5-sakana", "魚", "さかな", "fish", "魚は新鮮です。", "The fish is fresh."],
    ["v-n5-oishii", "おいしい", "おいしい", "delicious", "この料理はおいしいです。", "This dish is delicious."],
    ["v-n5-kudasai", "ください", "ください", "please give me", "メニューをください。", "A menu, please."],
  ]),
];

const n4Vocabulary = [
  ...words("N4", "Daily routines", [
    ["v-n4-kaisha", "会社", "かいしゃ", "company; office", "会社は九時に始まります。", "The office starts at nine."],
    ["v-n4-kaigi", "会議", "かいぎ", "meeting", "午後に会議があります。", "There is a meeting in the afternoon."],
    ["v-n4-shiryou", "資料", "しりょう", "materials; documents", "会議の資料を読みます。", "I read the meeting materials."],
    ["v-n4-shigoto", "仕事", "しごと", "work; job", "仕事が終わりました。", "Work has finished."],
    ["v-n4-shusshin", "出身", "しゅっしん", "hometown; origin", "ご出身はどこですか。", "Where are you from?"],
    ["v-n4-shumi", "趣味", "しゅみ", "hobby", "趣味は写真です。", "My hobby is photography."],
    ["v-n4-seikatsu", "生活", "せいかつ", "daily life; living", "日本の生活に慣れました。", "I have gotten used to life in Japan."],
    ["v-n4-shuukan", "習慣", "しゅうかん", "habit; custom", "毎朝歩くのは私の習慣です。", "Walking every morning is my habit."],
    ["v-n4-nareru", "慣れる", "なれる", "to get used to", "新しい仕事に慣れてきました。", "I am getting used to the new job."],
    ["v-n4-tsuzukeru", "続ける", "つづける", "to continue", "日本語の勉強を続けます。", "I will continue studying Japanese."],
    ["v-n4-kaeru", "変える", "かえる", "to change", "予約の時間を変えたいです。", "I want to change the reservation time."],
    ["v-n4-wasureru", "忘れる", "わすれる", "to forget", "かさを忘れました。", "I forgot my umbrella."],
    ["v-n4-oboeru", "覚える", "おぼえる", "to remember; learn", "新しい言葉を覚えます。", "I learn new words."],
  ]),
  ...words("N4", "Plans", [
    ["v-n4-yotei", "予定", "よてい", "plan; schedule", "週末の予定はありますか。", "Do you have plans for the weekend?"],
    ["v-n4-yoyaku-suru", "予約する", "よやくする", "to reserve; book", "ホテルを予約しました。", "I reserved a hotel."],
    ["v-n4-kimeru", "決める", "きめる", "to decide", "出発の時間を決めましょう。", "Let’s decide the departure time."],
    ["v-n4-riyuu", "理由", "りゆう", "reason", "遅れた理由を説明します。", "I will explain the reason I was late."],
    ["v-n4-kekka", "結果", "けっか", "result", "試験の結果を待っています。", "I am waiting for the test results."],
    ["v-n4-taisetsu", "大切", "たいせつ", "important; precious", "健康は大切です。", "Health is important."],
    ["v-n4-kibun", "気分", "きぶん", "feeling; mood", "今日は気分がいいです。", "I feel good today."],
    ["v-n4-setsumei", "説明", "せつめい", "explanation", "もう一度説明してください。", "Please explain one more time."],
    ["v-n4-oshieru", "教える", "おしえる", "to teach; tell", "駅への道を教えてください。", "Please tell me the way to the station."],
    ["v-n4-tasukeru", "助ける", "たすける", "to help", "重い荷物を助けてくれました。", "They helped me with the heavy luggage."],
    ["v-n4-erabu", "選ぶ", "えらぶ", "to choose", "好きなコースを選んでください。", "Please choose the course you like."],
    ["v-n4-narau", "習う", "ならう", "to learn from someone", "先生に日本語を習っています。", "I am learning Japanese from a teacher."],
  ]),
  ...words("N4", "Getting around", [
    ["v-n4-shuppatsu", "出発", "しゅっぱつ", "departure", "電車は八時に出発します。", "The train departs at eight."],
    ["v-n4-touchaku", "到着", "とうちゃく", "arrival", "東京に午後三時に到着します。", "We arrive in Tokyo at three in the afternoon."],
    ["v-n4-untenshu", "運転手", "うんてんしゅ", "driver", "運転手に聞きました。", "I asked the driver."],
    ["v-n4-jiko", "事故", "じこ", "accident", "事故で電車が遅れています。", "The train is delayed because of an accident."],
    ["v-n4-kado", "角", "かど", "corner", "次の角を左に曲がります。", "Turn left at the next corner."],
    ["v-n4-shingou", "信号", "しんごう", "traffic light", "信号の前で止まってください。", "Please stop in front of the traffic light."],
    ["v-n4-tokkyuu", "特急", "とっきゅう", "limited express", "特急はこの駅に止まりません。", "The limited express does not stop at this station."],
    ["v-n4-futsuu", "普通", "ふつう", "local; ordinary", "普通電車で行きます。", "I will go by local train."],
    ["v-n4-ryokin", "料金", "りょうきん", "fee; fare", "入場料金はいくらですか。", "How much is the admission fee?"],
    ["v-n4-tomaru", "泊まる", "とまる", "to stay overnight", "京都のホテルに泊まります。", "I will stay at a hotel in Kyoto."],
    ["v-n4-kankou", "観光", "かんこう", "sightseeing", "明日は京都を観光します。", "Tomorrow I will sightsee in Kyoto."],
    ["v-n4-annan", "案内", "あんない", "guidance; guide", "駅で観光案内をもらいました。", "I got sightseeing information at the station."],
  ]),
  ...words("N4", "Shopping", [
    ["v-n4-ryoushuusho", "領収書", "りょうしゅうしょ", "receipt", "領収書をください。", "Please give me a receipt."],
    ["v-n4-henpin", "返品", "へんぴん", "returning goods", "この服を返品したいです。", "I want to return these clothes."],
    ["v-n4-koukan", "交換", "こうかん", "exchange", "違うサイズと交換できますか。", "Can I exchange it for a different size?"],
    ["v-n4-oshiharai", "支払い", "しはらい", "payment", "支払いはカードでできますか。", "Can I pay by card?"],
    ["v-n4-ginkouin", "銀行員", "ぎんこういん", "bank clerk", "銀行員に相談しました。", "I consulted a bank clerk."],
    ["v-n4-kowareru", "壊れる", "こわれる", "to break", "この機械は壊れています。", "This machine is broken."],
    ["v-n4-naosu", "直す", "なおす", "to fix; correct", "時計を直してもらいました。", "I had my watch fixed."],
    ["v-n4-uketsuke", "受付", "うけつけ", "reception; front desk", "受付で名前を書いてください。", "Please write your name at reception."],
    ["v-n4-ukeru", "受ける", "うける", "to receive; take", "来月、試験を受けます。", "I will take an exam next month."],
    ["v-n4-hara-u", "払う", "はらう", "to pay", "現金で払いました。", "I paid in cash."],
    ["v-n4-genkin", "現金", "げんきん", "cash", "現金だけですか。", "Is it cash only?"],
  ]),
  ...words("N4", "Eating out", [
    ["v-n4-ryouri", "料理", "りょうり", "cooking; dish", "この店は魚料理が有名です。", "This restaurant is famous for fish dishes."],
    ["v-n4-yoyaku-nashi", "予約なし", "よやくなし", "without a reservation", "予約なしでも入れますか。", "Can we enter without a reservation?"],
    ["v-n4-kibou", "希望", "きぼう", "wish; preference", "窓の近くの席を希望します。", "I would prefer a seat near the window."],
    ["v-n4-koucha", "紅茶", "こうちゃ", "black tea", "食後に紅茶を頼みます。", "I will order black tea after the meal."],
    ["v-n4-seki", "席", "せき", "seat", "禁煙席はありますか。", "Do you have non-smoking seats?"],
    ["v-n4-kinnen", "禁煙", "きんえん", "no smoking; non-smoking", "ここは禁煙です。", "Smoking is prohibited here."],
    ["v-n4-yakimono", "焼き物", "やきもの", "grilled food; pottery", "焼き物の魚を注文しました。", "I ordered grilled fish."],
    ["v-n4-ryou", "量", "りょう", "amount; portion", "ご飯の量を少なくしてください。", "Please make the rice portion smaller."],
  ]),
  ...words("N4", "Travel preparation", [
    ["v-n4-pasupooto", "パスポート", "ぱすぽーと", "passport", "パスポートを確認してください。", "Please check your passport."],
    ["v-n4-nimotsu", "荷物", "にもつ", "luggage; baggage", "荷物を預けたいです。", "I want to check my luggage."],
    ["v-n4-jusho", "住所", "じゅうしょ", "address", "住所をここに書いてください。", "Please write your address here."],
    ["v-n4-kokusai", "国際", "こくさい", "international", "国際線のカウンターは二階です。", "The international-flight counter is on the second floor."],
    ["v-n4-byouki", "病気", "びょうき", "illness", "旅行中に病気になりました。", "I became ill during the trip."],
    ["v-n4-kusuri", "薬", "くすり", "medicine", "この薬を一日三回飲んでください。", "Please take this medicine three times a day."],
    ["v-n4-hoken", "保険", "ほけん", "insurance", "旅行保険に入りました。", "I got travel insurance."],
  ]),
];

const n5Kanji = [
  ...kanji("N5", "Introductions", [
    ["k-n5-watashi", "私", "シ · わたし", "I; private", "私の名前（わたしのなまえ）", "my name"],
    ["k-n5-gaku", "学", "ガク · まなぶ", "study; learning", "学生（がくせい）", "student"],
    ["k-n5-sei", "生", "セイ · いきる", "life; birth", "先生（せんせい）", "teacher"],
    ["k-n5-mei", "名", "メイ · な", "name", "名前（なまえ）", "name"],
    ["k-n5-go", "語", "ゴ", "language; word", "日本語（にほんご）", "Japanese language"],
    ["k-n5-tomo", "友", "ユウ · とも", "friend", "友達（ともだち）", "friend"],
    ["k-n5-fu", "父", "フ · ちち", "father", "父（ちち）", "my father"],
    ["k-n5-bo", "母", "ボ · はは", "mother", "母（はは）", "my mother"],
  ]),
  ...kanji("N5", "Everyday Japanese", [
    ["k-n5-nichi", "日", "ニチ · ひ", "day; sun", "日曜日（にちようび）", "Sunday"],
    ["k-n5-nen", "年", "ネン · とし", "year", "今年（ことし）", "this year"],
    ["k-n5-ima", "今", "コン · いま", "now", "今週（こんしゅう）", "this week"],
    ["k-n5-mei2", "明", "メイ · あかるい", "bright; clear", "明日（あした）", "tomorrow"],
    ["k-n5-den", "電", "デン", "electricity", "電話（でんわ）", "telephone"],
    ["k-n5-sho", "書", "ショ · かく", "write", "図書館（としょかん）", "library"],
    ["k-n5-ji", "字", "ジ", "letter; character", "漢字（かんじ）", "kanji"],
  ]),
  ...kanji("N5", "Daily routines", [
    ["k-n5-asa", "朝", "チョウ · あさ", "morning", "朝ご飯（あさごはん）", "breakfast"],
    ["k-n5-hiru", "昼", "チュウ · ひる", "noon", "昼休み（ひるやすみ）", "lunch break"],
    ["k-n5-ya", "夜", "ヤ · よる", "night", "今夜（こんや）", "tonight"],
    ["k-n5-toki", "時", "ジ · とき", "hour; time", "三時（さんじ）", "three o’clock"],
    ["k-n5-fun", "分", "フン · わける", "minute; divide", "五分（ごふん）", "five minutes"],
    ["k-n5-kyuu", "休", "キュウ · やすむ", "rest", "休日（きゅうじつ）", "holiday"],
  ]),
  ...kanji("N5", "Getting around", [
    ["k-n5-kou", "校", "コウ", "school", "学校（がっこう）", "school"],
    ["k-n5-byoo", "病", "ビョウ · やむ", "illness", "病院（びょういん）", "hospital"],
    ["k-n5-in", "院", "イン", "institution", "病院（びょういん）", "hospital"],
    ["k-n5-migi", "右", "ウ · みぎ", "right", "右側（みぎがわ）", "right side"],
    ["k-n5-hidari", "左", "サ · ひだり", "left", "左側（ひだりがわ）", "left side"],
    ["k-n5-mae", "前", "ゼン · まえ", "front; before", "駅前（えきまえ）", "in front of the station"],
    ["k-n5-ugo", "後", "ゴ · うしろ", "after; behind", "午後（ごご）", "afternoon"],
  ]),
  ...kanji("N5", "Shopping", [
    ["k-n5-en", "円", "エン", "yen; circle", "百円（ひゃくえん）", "100 yen"],
    ["k-n5-taka", "高", "コウ · たかい", "high; expensive", "高い（たかい）", "expensive"],
    ["k-n5-yasu", "安", "アン · やすい", "cheap; safe", "安い（やすい）", "inexpensive"],
  ]),
];

const n4Kanji = [
  ...kanji("N4", "Daily routines", [
    ["k-n4-shuu", "週", "シュウ", "week", "来週（らいしゅう）", "next week"],
    ["k-n4-kyou", "教", "キョウ · おしえる", "teach", "教室（きょうしつ）", "classroom"],
    ["k-n4-shuu2", "習", "シュウ · ならう", "learn; practice", "練習（れんしゅう）", "practice"],
    ["k-n4-zu", "図", "ズ", "diagram; plan", "地図（ちず）", "map"],
    ["k-n4-kan", "館", "カン", "building; hall", "図書館（としょかん）", "library"],
    ["k-n4-ki", "記", "キ · しるす", "record; write down", "日記（にっき）", "diary"],
    ["k-n4-hatsu", "発", "ハツ", "depart; emit", "出発（しゅっぱつ）", "departure"],
    ["k-n4-shin", "進", "シン · すすむ", "advance", "進みます（すすみます）", "go forward"],
  ]),
  ...kanji("N4", "Plans", [
    ["k-n4-yo", "予", "ヨ", "in advance", "予定（よてい）", "schedule"],
    ["k-n4-tei", "定", "テイ · さだめる", "decide; fixed", "予定（よてい）", "schedule"],
    ["k-n4-ketsu", "決", "ケツ · きめる", "decide", "決める（きめる）", "to decide"],
    ["k-n4-ri", "理", "リ", "reason; logic", "理由（りゆう）", "reason"],
    ["k-n4-yuu", "由", "ユウ · よる", "reason; origin", "自由（じゆう）", "freedom"],
    ["k-n4-ken", "験", "ケン", "test; experience", "経験（けいけん）", "experience"],
    ["k-n4-cho", "調", "チョウ · しらべる", "investigate; tune", "調べる（しらべる）", "to investigate"],
  ]),
  ...kanji("N4", "Getting around", [
    ["k-n4-un", "運", "ウン · はこぶ", "carry; luck", "運転（うんてん）", "driving"],
    ["k-n4-ten", "転", "テン · ころがる", "turn; roll", "運転手（うんてんしゅ）", "driver"],
    ["k-n4-dou", "道", "ドウ · みち", "road; way", "道案内（みちあんない）", "directions"],
    ["k-n4-shin2", "信", "シン", "trust; signal", "信号（しんごう）", "traffic light"],
    ["k-n4-gou", "号", "ゴウ", "number; signal", "信号（しんごう）", "traffic light"],
    ["k-n4-kan2", "観", "カン", "observe", "観光（かんこう）", "sightseeing"],
    ["k-n4-kou2", "光", "コウ · ひかる", "light", "観光（かんこう）", "sightseeing"],
    ["k-n4-tsu", "着", "チャク · つく", "arrive; wear", "到着（とうちゃく）", "arrival"],
  ]),
  ...kanji("N4", "Shopping", [
    ["k-n4-shi", "支", "シ · ささえる", "support; pay", "支払い（しはらい）", "payment"],
    ["k-n4-hen", "返", "ヘン · かえす", "return", "返品（へんぴん）", "returning goods"],
    ["k-n4-ryou", "領", "リョウ", "territory; receive", "領収書（りょうしゅうしょ）", "receipt"],
    ["k-n4-kin", "現", "ゲン · あらわれる", "present; appear", "現金（げんきん）", "cash"],
    ["k-n4-kin2", "禁", "キン", "prohibit", "禁煙（きんえん）", "no smoking"],
    ["k-n4-en2", "煙", "エン · けむり", "smoke", "禁煙（きんえん）", "no smoking"],
  ]),
  ...kanji("N4", "Travel preparation", [
    ["k-n4-juu", "住", "ジュウ · すむ", "live; reside", "住所（じゅうしょ）", "address"],
    ["k-n4-ka", "荷", "カ · に", "luggage; burden", "荷物（にもつ）", "luggage"],
    ["k-n4-yaku", "薬", "ヤク · くすり", "medicine", "薬局（やっきょく）", "pharmacy"],
    ["k-n4-ho", "保", "ホ · たもつ", "protect", "保険（ほけん）", "insurance"],
    ["k-n4-ken2", "険", "ケン", "risky; steep", "保険（ほけん）", "insurance"],
    ["k-n4-koku", "国", "コク · くに", "country", "国際（こくさい）", "international"],
  ]),
];

const grammar: CurriculumDraft[] = [
  { id: "g-n5-ga", type: "grammar", expression: "〜が", reading: "が", meaning: "subject marker; but", level: "N5", example: "猫がいます。", exampleMeaning: "There is a cat.", note: "が often marks newly introduced information or the subject that exists. At this level, learn it alongside は rather than treating them as interchangeable.", topic: "Everyday Japanese" },
  { id: "g-n5-no", type: "grammar", expression: "〜の", reading: "の", meaning: "possession; connection", level: "N5", example: "これは私の本です。", exampleMeaning: "This is my book.", note: "Put の between two nouns to connect them: AのB means B of A or A’s B.", topic: "Introductions" },
  { id: "g-n5-mo", type: "grammar", expression: "〜も", reading: "も", meaning: "also; too", level: "N5", example: "私も学生です。", exampleMeaning: "I am also a student.", note: "Use も in place of は or が when adding someone or something to the same statement.", topic: "Introductions" },
  { id: "g-n5-kore-sore-are", type: "grammar", expression: "これ／それ／あれ", reading: "これ それ あれ", meaning: "this / that / that over there", level: "N5", example: "これは私のです。", exampleMeaning: "This one is mine.", note: "Choose by distance: これ near the speaker, それ near the listener, あれ away from both.", topic: "Everyday Japanese" },
  { id: "g-n5-i-adj", type: "grammar", expression: "い-adjective + です", reading: "けいようし", meaning: "polite adjective statement", level: "N5", example: "このかばんは高いです。", exampleMeaning: "This bag is expensive.", note: "An い-adjective can come directly before です. For its past form, change い to かった: 高かったです.", topic: "Shopping" },
  { id: "g-n5-na-adj", type: "grammar", expression: "な-adjective + です", reading: "なけいようし", meaning: "polite adjective statement", level: "N5", example: "この町は静かです。", exampleMeaning: "This town is quiet.", note: "Use な before a noun, as in 静かな町. Do not add な before です.", topic: "Everyday Japanese" },
  { id: "g-n5-ta", type: "grammar", expression: "〜ました", reading: "ました", meaning: "polite past", level: "N5", example: "昨日、映画を見ました。", exampleMeaning: "Yesterday, I watched a movie.", note: "Replace ます with ました to describe a completed action politely.", topic: "Daily routines" },
  { id: "g-n5-masen-deshita", type: "grammar", expression: "〜ませんでした", reading: "ませんでした", meaning: "polite past negative", level: "N5", example: "昨日は勉強しませんでした。", exampleMeaning: "I did not study yesterday.", note: "Use ませんでした for an action that did not happen in the past.", topic: "Daily routines" },
  { id: "g-n5-te-iru", type: "grammar", expression: "〜ています", reading: "ています", meaning: "is doing; habitual state", level: "N5", example: "今、日本語を勉強しています。", exampleMeaning: "I am studying Japanese now.", note: "The て-form plus います can describe an action in progress or a continuing state, depending on the verb.", topic: "Daily routines" },
  { id: "g-n5-mashou", type: "grammar", expression: "〜ましょう", reading: "ましょう", meaning: "let’s …", level: "N5", example: "一緒に行きましょう。", exampleMeaning: "Let’s go together.", note: "Replace ます with ましょう to make a polite invitation or suggestion.", topic: "Getting around" },
  { id: "g-n5-kara-made", type: "grammar", expression: "〜から〜まで", reading: "から まで", meaning: "from … to …", level: "N5", example: "店は九時から六時までです。", exampleMeaning: "The shop is open from nine to six.", note: "Use から for the start and まで for the end of a time or place range.", topic: "Shopping" },
  { id: "g-n5-ni-arimasu", type: "grammar", expression: "place に thing が あります", reading: "に あります", meaning: "there is … at/in …", level: "N5", example: "机の上に本があります。", exampleMeaning: "There is a book on the desk.", note: "Use this pattern for inanimate things. With people and animals, use います instead.", topic: "Everyday Japanese" },
  { id: "g-n5-count", type: "grammar", expression: "number + counter", reading: "かぞえかた", meaning: "counting objects", level: "N5", example: "りんごを三つ買いました。", exampleMeaning: "I bought three apples.", note: "Japanese uses counters after numbers. Start with ひとつ, ふたつ, みっつ for general objects.", topic: "Shopping" },
  { id: "g-n5-suki", type: "grammar", expression: "〜が好きです", reading: "が すきです", meaning: "to like …", level: "N5", example: "私は音楽が好きです。", exampleMeaning: "I like music.", note: "The thing liked is marked with が in this pattern, even though English uses a direct object.", topic: "Introductions" },
  { id: "g-n4-te-iru-state", type: "grammar", expression: "〜ている (state)", reading: "ている", meaning: "resulting state", level: "N4", example: "窓が開いています。", exampleMeaning: "The window is open.", note: "With many change-of-state verbs, ている describes the resulting condition rather than an action in progress.", topic: "Daily routines" },
  { id: "g-n4-te-iku", type: "grammar", expression: "〜ていく", reading: "ていく", meaning: "go on doing; move away", level: "N4", example: "これからも日本語を勉強していきます。", exampleMeaning: "I will keep studying Japanese from now on.", note: "ていく often looks forward from the present, describing a process that will continue.", topic: "Plans" },
  { id: "g-n4-te-kuru", type: "grammar", expression: "〜てくる", reading: "てくる", meaning: "come to do; move toward", level: "N4", example: "少し分かってきました。", exampleMeaning: "I have started to understand a little.", note: "てくる often describes a change that has developed up to the present moment.", topic: "Daily routines" },
  { id: "g-n4-deshou", type: "grammar", expression: "〜でしょう", reading: "でしょう", meaning: "probably; isn’t it?", level: "N4", example: "明日は晴れるでしょう。", exampleMeaning: "It will probably be sunny tomorrow.", note: "でしょう softens a prediction or seeks gentle agreement, depending on intonation.", topic: "Plans" },
  { id: "g-n4-kamoshirenai", type: "grammar", expression: "〜かもしれない", reading: "かもしれない", meaning: "might; may", level: "N4", example: "電車が遅れるかもしれません。", exampleMeaning: "The train might be late.", note: "Attach かもしれない to a plain-form statement to express possibility.", topic: "Getting around" },
  { id: "g-n4-hou-ga", type: "grammar", expression: "〜ほうがいい", reading: "ほうがいい", meaning: "had better; should", level: "N4", example: "早く予約したほうがいいです。", exampleMeaning: "You should reserve early.", note: "Use past plain form + ほうがいい for advice to do something. Use ないほうがいい for advice not to.", topic: "Travel preparation" },
  { id: "g-n4-tara", type: "grammar", expression: "〜たら", reading: "たら", meaning: "if; when", level: "N4", example: "駅に着いたら、電話してください。", exampleMeaning: "When you arrive at the station, please call.", note: "Make the たら conditional from a verb’s plain past form, such as 着いたら.", topic: "Getting around" },
  { id: "g-n4-nara", type: "grammar", expression: "〜なら", reading: "なら", meaning: "if it is …; as for …", level: "N4", example: "京都なら、春がおすすめです。", exampleMeaning: "If it is Kyoto, spring is recommended.", note: "なら responds to a topic or condition already raised in the conversation.", topic: "Plans" },
  { id: "g-n4-node", type: "grammar", expression: "〜ので", reading: "ので", meaning: "because; since", level: "N4", example: "雨なので、タクシーで行きます。", exampleMeaning: "Because it is raining, I will go by taxi.", note: "ので gives a reason with a slightly softer, more explanatory feel than から.", topic: "Getting around" },
  { id: "g-n4-noni", type: "grammar", expression: "〜のに", reading: "のに", meaning: "although; despite", level: "N4", example: "安いのに、おいしいです。", exampleMeaning: "Although it is cheap, it is delicious.", note: "のに presents a result that is surprising or contrary to expectation.", topic: "Eating out" },
  { id: "g-n4-you-ni", type: "grammar", expression: "〜ように", reading: "ように", meaning: "so that; like", level: "N4", example: "忘れないように、メモします。", exampleMeaning: "I make a note so that I will not forget.", note: "Use dictionary form or negative form before ように when expressing a goal, especially one outside direct control.", topic: "Daily routines" },
  { id: "g-n4-koto-ni-suru", type: "grammar", expression: "〜ことにする", reading: "ことにする", meaning: "decide to …", level: "N4", example: "毎日十分勉強することにしました。", exampleMeaning: "I decided to study ten minutes every day.", note: "Use dictionary form or ない form + ことにする for a personal decision.", topic: "Plans" },
  { id: "g-n4-koto-ni-naru", type: "grammar", expression: "〜ことになる", reading: "ことになる", meaning: "it has been decided that …", level: "N4", example: "来月、大阪へ行くことになりました。", exampleMeaning: "It has been decided that I will go to Osaka next month.", note: "Use this when a decision is made by circumstances, an organization, or another person rather than solely by you.", topic: "Plans" },
  { id: "g-n4-nakute-mo-ii", type: "grammar", expression: "〜なくてもいい", reading: "なくてもいい", meaning: "do not have to …", level: "N4", example: "明日は来なくてもいいです。", exampleMeaning: "You do not have to come tomorrow.", note: "Use the negative ない form without い, plus くてもいい, to say something is unnecessary.", topic: "Daily routines" },
  { id: "g-n4-te-ageru", type: "grammar", expression: "〜てあげる", reading: "てあげる", meaning: "do … for someone", level: "N4", example: "友達に道を教えてあげます。", exampleMeaning: "I will tell my friend the way.", note: "Use with care: it highlights a favor you do for someone else and can sound self-important in some contexts.", topic: "Getting around" },
  { id: "g-n4-te-kureru", type: "grammar", expression: "〜てくれる", reading: "てくれる", meaning: "someone does … for me/us", level: "N4", example: "駅員さんが助けてくれました。", exampleMeaning: "The station staff member helped me.", note: "Use when another person’s action benefits you or your in-group.", topic: "Getting around" },
  { id: "g-n4-te-morau", type: "grammar", expression: "〜てもらう", reading: "てもらう", meaning: "receive the favor of …", level: "N4", example: "先生に説明してもらいました。", exampleMeaning: "I had the teacher explain it to me.", note: "The person who helps is marked with に, and you receive the benefit of the action.", topic: "Daily routines" },
  { id: "g-n4-bakari", type: "grammar", expression: "〜ばかり", reading: "ばかり", meaning: "only; just did", level: "N4", example: "日本に来たばかりです。", exampleMeaning: "I have just come to Japan.", note: "Past plain form + ばかり means that an action happened only a short time ago.", topic: "Travel preparation" },
];

const passages: CurriculumDraft[] = [
  { id: "r-n5-schedule", type: "reading", expression: "授業の予定", reading: "じゅぎょうのよてい", meaning: "Class schedule", level: "N5", example: "日本語の授業は月曜日と水曜日です。時間は午後二時から三時半までです。", exampleMeaning: "Japanese class is on Monday and Wednesday. It is from 2:00 to 3:30 p.m.", note: "Read times and days first. They often provide the answer without translating every sentence.", topic: "Daily routines", question: "On which days is the Japanese class?", answer: "Monday and Wednesday." },
  { id: "r-n5-form", type: "reading", expression: "簡単な申込書", reading: "かんたんなもうしこみしょ", meaning: "A simple application form", level: "N5", example: "名前：スミス ダニエル\n国：アメリカ\n電話：090-1234-5678", exampleMeaning: "Name: Smith Daniel\nCountry: United States\nPhone: 090-1234-5678", note: "Forms use labels instead of full sentences. Match each label with the correct personal detail.", topic: "Introductions", question: "What country is listed on the form?", answer: "The United States." },
  { id: "r-n5-directions", type: "reading", expression: "駅から学校まで", reading: "えきからがっこうまで", meaning: "From the station to school", level: "N5", example: "駅を出て、右に曲がってください。二つ目の信号の前に学校があります。", exampleMeaning: "Leave the station and turn right. The school is in front of the second traffic light.", note: "Follow direction words in order: leave, turn, then find the landmark.", topic: "Getting around", question: "Where is the school?", answer: "In front of the second traffic light." },
  { id: "r-n5-receipt", type: "reading", expression: "レシート", reading: "れしーと", meaning: "Receipt", level: "N5", example: "パン　150円\n水　100円\n合計　250円", exampleMeaning: "Bread 150 yen\nWater 100 yen\nTotal 250 yen", note: "For a receipt, connect each item with its price and check the total.", topic: "Shopping", question: "How much is the water?", answer: "100 yen." },
  { id: "r-n4-hotel", type: "reading", expression: "ホテルからのメール", reading: "ほてるからのめーる", meaning: "Email from a hotel", level: "N4", example: "ご予約ありがとうございます。チェックインは午後三時からです。予定より遅くなる場合は、ホテルまでご連絡ください。", exampleMeaning: "Thank you for your reservation. Check-in is from 3 p.m. If you will be later than planned, please contact the hotel.", note: "Practical messages often have a condition and an action. Find what triggers the action, then what you should do.", topic: "Travel preparation", question: "What should the guest do if they will arrive late?", answer: "Contact the hotel." },
  { id: "r-n4-weather", type: "reading", expression: "週末の天気", reading: "しゅうまつのてんき", meaning: "Weekend weather", level: "N4", example: "土曜日は晴れるでしょう。日曜日は雨かもしれませんから、かさを持って行ったほうがいいです。", exampleMeaning: "Saturday will probably be sunny. It might rain on Sunday, so it is better to bring an umbrella.", note: "Notice the degree of certainty: でしょう is a prediction and かもしれません is a possibility.", topic: "Plans", question: "Why is it better to bring an umbrella?", answer: "Because it might rain on Sunday." },
  { id: "r-n4-lost", type: "reading", expression: "落とし物のお知らせ", reading: "おとしもののおしらせ", meaning: "Lost-property notice", level: "N4", example: "青いかばんをお預かりしています。心当たりのある方は、午後六時までに駅の受付へ来てください。", exampleMeaning: "We are holding a blue bag. If you think it may be yours, please come to the station reception by 6 p.m.", note: "Notices may use formal verbs such as お預かりしています. Focus on the item, location, and deadline.", topic: "Getting around", question: "Where should the owner of the bag go?", answer: "To the station reception." },
  { id: "r-n4-return", type: "reading", expression: "返品について", reading: "へんぴんについて", meaning: "About returns", level: "N4", example: "商品を買ってから七日以内なら、レシートを持って返品できます。ただし、使った商品は返品できません。", exampleMeaning: "If it is within seven days of purchase, you can return an item with the receipt. However, used items cannot be returned.", note: "Look for the rule, its time limit, and any exception introduced by ただし.", topic: "Shopping", question: "Can a used item be returned?", answer: "No, used items cannot be returned." },
];

const listening: CurriculumDraft[] = [
  { id: "l-n5-class", type: "listening", expression: "授業の会話", reading: "じゅぎょうのかいわ", meaning: "Conversation about class", level: "N5", example: "A：明日の日本語の授業は何時ですか。B：二時です。でも、一時半に教室に来てください。", exampleMeaning: "A: What time is tomorrow’s Japanese class? B: It is at two. But please come to the classroom at one thirty.", note: "Listening-script item. First listen for the class time, then listen again for the earlier arrival time.", topic: "Daily routines", question: "What time should the listener come to the classroom?", answer: "At 1:30." },
  { id: "l-n5-order", type: "listening", expression: "注文する", reading: "ちゅうもんする", meaning: "Placing an order", level: "N5", example: "店員：ご注文は。客：水とコーヒーを一つずつお願いします。", exampleMeaning: "Server: What would you like? Customer: One water and one coffee, please.", note: "Listening-script item. Listen for the items and for 一つずつ, which means one of each.", topic: "Eating out", question: "What does the customer order?", answer: "One water and one coffee." },
  { id: "l-n5-lost", type: "listening", expression: "駅で聞く", reading: "えきできく", meaning: "Asking at the station", level: "N5", example: "すみません、銀行はどこですか。駅を出て、左です。", exampleMeaning: "Excuse me, where is the bank? Leave the station and it is on the left.", note: "Listening-script item. Identify the starting point and the single direction.", topic: "Getting around", question: "Where is the bank?", answer: "On the left after leaving the station." },
  { id: "l-n4-change", type: "listening", expression: "予約の変更", reading: "よやくのへんこう", meaning: "Changing a reservation", level: "N4", example: "A：明日の予約を七時から八時に変えられますか。B：はい、空いていますので大丈夫です。", exampleMeaning: "A: Can I change tomorrow’s reservation from seven to eight? B: Yes, it is available, so that is fine.", note: "Listening-script item. Track both the original time and the requested new time.", topic: "Plans", question: "What new time is requested?", answer: "Eight o’clock." },
  { id: "l-n4-delay", type: "listening", expression: "電車の遅れ", reading: "でんしゃのおくれ", meaning: "Train delay", level: "N4", example: "事故のため、この電車は十分ほど遅れています。ご迷惑をおかけして申し訳ありません。", exampleMeaning: "Because of an accident, this train is delayed by about ten minutes. We apologize for the inconvenience.", note: "Listening-script item. Announcements often lead with the cause, followed by the delay length.", topic: "Getting around", question: "How long is the train delayed?", answer: "About ten minutes." },
  { id: "l-n4-pharmacy", type: "listening", expression: "薬局で", reading: "やっきょくで", meaning: "At a pharmacy", level: "N4", example: "薬剤師：この薬は食後に飲んでください。A：一日に何回ですか。薬剤師：三回です。", exampleMeaning: "Pharmacist: Please take this medicine after meals. A: How many times a day? Pharmacist: Three times.", note: "Listening-script item. Catch the timing of the medicine and the frequency separately.", topic: "Travel preparation", question: "How many times a day should the medicine be taken?", answer: "Three times a day." },
];

export const expandedCurriculum: CurriculumDraft[] = [
  ...n5Vocabulary,
  ...n4Vocabulary,
  ...n5Kanji,
  ...n4Kanji,
  ...grammar,
  ...passages,
  ...listening,
];
