import { writeFile } from "node:fs/promises";
import vocabularyData from "../src/lib/study/data/jlpt-n5-n4-vocabulary.json";
import { validateVocabularyDataset } from "../src/lib/study/vocabulary-data";

const result = validateVocabularyDataset(vocabularyData);
const queue = result.data.items
  .map((item) => ({
    id: item.id,
    expression: item.expression,
    reading: item.reading,
    level: item.level,
    issues: result.flags.filter((flag) => flag.startsWith(`${item.id}:`)),
  }))
  .filter((item) => item.issues.length);
const fallbackExamples = result.data.items.filter(
  (item) => item.vocabulary.provenance.exampleKind === "fallback",
).length;
const uncertainFurigana = result.data.items.filter(
  (item) => item.vocabulary.review.furigana === "uncertain",
).length;
const missingTargets = queue.filter((item) =>
  item.issues.some((issue) => issue.includes("target span")),
).length;
const markdown = [
  "# Vocabulary data-quality report",
  "",
  "Generated by `scripts/report-vocabulary-quality.ts`. This Phase 2 report separates structural validity from linguistic review; a passing structure check does not certify Japanese quality.",
  "",
  "| Measurement | Result |",
  "| --- | ---: |",
  `| Active N5 records | ${result.data.counts.n5} |`,
  `| Active N4-only records | ${result.data.counts.n4Only} |`,
  `| Active total | ${result.data.counts.total} |`,
  `| Retired records | ${result.data.retired.length} |`,
  `| Structural validation errors | ${result.issues.length} |`,
  `| Repeated example groups | ${result.duplicateExamples.length} |`,
  `| Records in editorial review queue | ${queue.length} |`,
  `| Fallback examples | ${fallbackExamples} |`,
  `| Uncertain furigana segmentations | ${uncertainFurigana} |`,
  `| Examples without an exact/recognized inflected target span | ${missingTargets} |`,
  "",
  "The complete machine-readable queue is `src/lib/study/data/vocabulary-review-queue.json`. Phase 3 must use its fixed sample and targeted flags to inspect Japanese, English, sense alignment, JLPT placement, provenance, and ruby output. Entries marked `reviewed` in this candidate were corrected in Phase 2; they have not received independent Phase 3 review.",
  "",
  "## Retired records",
  "",
  ...result.data.retired.map((item) => `- \`${item.id}\`: ${item.reason}`),
  "",
  "## Structural validation",
  "",
  result.issues.length
    ? result.issues.map((issue) => `- ${issue}`).join("\n")
    : "No malformed records, duplicate normalized expression/reading pairs, or ruby reconstruction failures were found.",
  "",
].join("\n");

async function main() {
  await Promise.all([
    writeFile("docs/data-quality-report.md", markdown),
    writeFile(
      "src/lib/study/data/vocabulary-review-queue.json",
      `${JSON.stringify(queue, null, 2)}\n`,
    ),
  ]);
}

void main();
