import { writeFile } from "node:fs/promises";
import vocabularyData from "../src/lib/study/data/jlpt-n5-n4-vocabulary.json";
import { validateVocabularyDataset } from "../src/lib/study/vocabulary-data";

const result = validateVocabularyDataset(vocabularyData);
const queue = result.data.items
  .map((item) => ({
    id: item.id,
    expression: item.expression,
    reading: item.reading,
    level: item.level,
    approved: item.vocabulary.approval.approved,
    approvalReasons: item.vocabulary.approval.reasons,
    issues: result.flags.filter((flag) => flag.startsWith(`${item.id}:`)),
  }))
  .filter((item) => item.issues.length || !item.approved);
const fallbackExamples = result.data.items.filter(
  (item) => item.vocabulary.provenance.example.kind === "fallback",
).length;
const unattributedImported = result.data.items.filter(
  (item) =>
    item.vocabulary.provenance.example.kind === "imported" &&
    !item.vocabulary.provenance.example.attribution,
).length;
const attributedExamples = result.data.items.filter(
  (item) => item.vocabulary.provenance.example.attribution,
).length;
const uncertainFurigana = result.data.items.filter(
  (item) => item.vocabulary.review.furigana === "uncertain",
).length;
const missingTargets = result.data.items.filter(
  (item) => !item.vocabulary.targetSpans.length,
).length;
const dictionaryMatched = result.data.items.filter(
  (item) => item.vocabulary.provenance.dictionary,
).length;
const unconfirmedSense = result.data.items.filter(
  (item) =>
    item.vocabulary.provenance.dictionary &&
    item.vocabulary.provenance.dictionary.glossOverlap === 0,
).length;
const approvalReasonCounts = new Map<string, number>();
for (const item of result.data.items)
  for (const reason of item.vocabulary.approval.reasons)
    approvalReasonCounts.set(reason, (approvalReasonCounts.get(reason) ?? 0) + 1);

const markdown = [
  "# Vocabulary data-quality report",
  "",
  "Generated by `scripts/report-vocabulary-quality.ts`. This report separates structural validity, mechanical approval, and linguistic review; a passing structure check does not certify Japanese quality, and mechanical approval is not a substitute for the Phase 3 line-by-line audit or the Phase 4 independent holdout.",
  "",
  "## Catalog vs. active",
  "",
  "| Measurement | Result |",
  "| --- | ---: |",
  `| Catalog N5 records (all candidates) | ${result.data.counts.n5} |`,
  `| Catalog N4-only records (all candidates) | ${result.data.counts.n4Only} |`,
  `| Catalog total | ${result.data.counts.total} |`,
  `| **Approved/active N5 records (what learners study)** | **${result.data.approvedCounts.n5}** |`,
  `| **Approved/active N4-only records (what learners study)** | **${result.data.approvedCounts.n4Only}** |`,
  `| **Approved/active total** | **${result.data.approvedCounts.total}** |`,
  `| Not approved (quarantined for Phase 3/4) | ${result.data.counts.total - result.data.approvedCounts.total} |`,
  `| Retired records | ${result.data.retired.length} |`,
  "",
  "## Structural and mechanical checks",
  "",
  "| Measurement | Result |",
  "| --- | ---: |",
  `| Structural validation errors | ${result.issues.length} |`,
  `| Repeated example groups | ${result.duplicateExamples.length} |`,
  `| Records in editorial review queue (unapproved or flagged) | ${queue.length} |`,
  `| Fallback (placeholder) examples remaining | ${fallbackExamples} |`,
  `| Examples without a validated target span | ${missingTargets} |`,
  `| Uncertain word/sentence furigana segmentations | ${uncertainFurigana} |`,
  "",
  "## Provenance",
  "",
  "| Measurement | Result |",
  "| --- | ---: |",
  `| Records matched to a full-JMdict entry | ${dictionaryMatched} of ${result.data.counts.total} |`,
  `| Matched entries with no confirmed sense (zero gloss overlap with the stored meaning) | ${unconfirmedSense} |`,
  `| Examples with recovered Tatoeba sentence attribution | ${attributedExamples} |`,
  `| Imported examples still lacking recovered attribution | ${unattributedImported} |`,
  "",
  "## Why records are not approved",
  "",
  "| Reason | Records |",
  "| --- | ---: |",
  ...[...approvalReasonCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([reason, count]) => `| ${reason} | ${count} |`),
  "",
  "The complete machine-readable queue is `src/lib/study/data/vocabulary-review-queue.json`, listing every unapproved or flagged record with its reasons. Use the fixed Phase 3 sample, the fresh Phase 4 holdout, and this queue to inspect Japanese, English, sense alignment, JLPT placement, provenance, and ruby output. Entries marked `reviewed` were corrected by an editorial pass; that status does not certify the full corpus or resolve example attribution.",
  "",
  "## Retired records",
  "",
  ...result.data.retired.map((item) => `- \`${item.id}\`: ${item.reason}`),
  "",
  "## Structural validation",
  "",
  result.issues.length
    ? result.issues.map((issue) => `- ${issue}`).join("\n")
    : "No malformed records, duplicate normalized expression/reading pairs, or ruby reconstruction failures were found.",
  "",
].join("\n");

async function main() {
  await Promise.all([
    writeFile("docs/data-quality-report.md", markdown),
    writeFile(
      "src/lib/study/data/vocabulary-review-queue.json",
      `${JSON.stringify(queue, null, 2)}\n`,
    ),
  ]);
}

void main();
